[package]
name = "media_info"
version = "0.1.3"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
quick-error = "1.2"


[features]
static=[]
partially-static=[]

